apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: default
  labels:
    app: laravel
type: Opaque
stringData:
  app-key: "base64:NSK3juYL5lT6RZOSc5bO5nZb5+4hWD4Pv8AA4g0T/Vk="
  redis-host: "redis-0.redis.default.svc.cluster.local"
  redis-password: ""
  redis-port: "6379"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-app
  namespace: default
  labels:
    app: laravel
